const db = require('../config/connection');
const { Profile, Verse, Order } = require('../models');
const profileSeeds = require('./profileSeeds.json');
const verseSeeds = require('./verseSeeds.json');
const cleanDB = require('./cleanDB');
const orderSeeds = require('./orderSeeds.json');

db.once('open', async () => {
  try {
   await cleanDB('Profile', 'profiles');
   await cleanDB('Verse', 'verses');
   await cleanDB('Order', 'orders');
   const profiles = await Profile.create(profileSeeds);
   const verses = await Verse.create(verseSeeds);
   const orders = await Order.create(orderSeeds);

    // add ordersSeed  - autogenerated

    console.log(profiles);
    console.log(verses);
    console.log(orders);
    console.info('Seeding complete! 🌱');

    console.log('all done!');
    process.exit(0);
  } catch (err) {
    throw err;
  }
});
